- packages/frontend/src/styles/vuetify.scss
Edit hover opacity for table cells and table buttons
Fixes #44
> feat: edit v-card default hover styles

- package-lock.json
- packages/frontend/src/components/common/inputs/BaseUserSelector.vue
- packages/frontend/src/components/common/navigation/UserListItem.vue
- packages/frontend/src/components/common/users/types.ts
- packages/frontend/src/components/project-management/cards/BaseCardActivityTimeline.vue
- packages/frontend/src/composables/services/useUsersService.ts
- packages/frontend/src/utils/string.ts
Search for specific users when selecting them through the `<base-user-selector />` component. Fixes #45
> Feat: Search Bar in User Selection Menu

- packages/backend/src/app/common/cards/card.entity.ts
- packages/backend/src/app/common/cards/dto/create.card.dto.ts
- packages/backend/src/config/typeorm.ts
- packages/backend/src/migrations/1717406725195-add-starts-at-column-to-cards-table.ts
- packages/frontend/src/components/common/dialogs/CreateCardDialog.vue
- packages/frontend/src/components/common/inputs/BaseDatePicker.vue
- packages/frontend/src/components/project-management/cards/BaseCard.vue
- packages/frontend/src/components/project-management/cards/types.ts
- packages/frontend/src/composables/useDate.ts
Set a starting date for a card along side its due date. Fixes #68
> Feature: Card Start Date

- packages/backend/src/app/common/lists/list-groups/list.groups.service.ts
> fix(filter): Update ListGroup generation functionality

- packages/frontend/src/components/common/auth/LoginPage.vue
- packages/frontend/src/components/common/auth/RegisterForm.vue
> Enhancement: Link Authentication Pages to Each Other

- packages/frontend/src/components/common/base/BaseEditor/extensions/Commands/suggestions.ts
- packages/frontend/src/components/common/commands/BaseCommandPalette.vue
- packages/frontend/src/components/common/inputs/BaseLabelSelector.vue
- packages/frontend/src/composables/useCommands.ts
- packages/frontend/src/utils/string.ts
> Enhancement: Choose Card Types to Create from Command Palette

- packages/backend/src/app/common/views/view.entity.ts
- packages/backend/src/app/common/views/views.service.ts
- packages/backend/src/migrations/1719224538052-add-ignoreCompleted-column-to-view-table.ts
- packages/frontend/src/components/common/inputs/BaseDatePicker.vue
- packages/frontend/src/components/project-management/views/BaseView.vue
- packages/frontend/src/components/project-management/views/BaseViewChipSort.vue
- packages/frontend/src/components/project-management/views/BoardView/BoardViewGroup.vue
- packages/frontend/src/components/project-management/views/ListView/ListViewGroup.vue
- packages/frontend/src/components/project-management/views/TableView/TableViewGroup.vue
- packages/frontend/src/components/project-management/views/types.ts
> style(fe-view): Style completed cards

- packages/frontend/src/components/common/inputs/BaseDatePicker.vue
- packages/frontend/src/components/project-management/cards/BaseCardPropertyValueBtn.vue
- packages/frontend/src/components/project-management/cards/types.ts
- packages/frontend/src/components/project-management/views/BaseView.vue
- packages/frontend/src/components/project-management/views/BoardView/BoardViewGroup.vue
- packages/frontend/src/components/project-management/views/ListView/ListViewGroup.vue
- packages/frontend/src/components/project-management/views/TableView/TableViewGroup.vue
- packages/frontend/src/plugins/vuetify.ts
> feat: clear date picker value

- packages/frontend/src/components/project-management/views/BaseView.vue
> fix: delete tasks confirmation dialog not opening

- packages/frontend/src/components/project-management/views/BoardView/BoardViewGroup.vue
- packages/frontend/src/components/project-management/views/ListView/ListViewGroup.vue
- packages/frontend/src/components/project-management/views/TableView/TableViewGroup.vue
> fix: handle end of dragging correctly when dragging cards

- packages/frontend/src/components/project-management/views/BaseView.vue
- packages/frontend/src/components/project-management/views/BoardView/BoardView.vue
- packages/frontend/src/components/project-management/views/BoardView/BoardViewGroup.vue
- packages/frontend/src/components/project-management/views/ListView/ListView.vue
- packages/frontend/src/components/project-management/views/TableView/TableView.vue
- packages/frontend/src/layouts/ProjectLayout.vue
> feat: add app bar on smaller screens

- packages/backend/src/app/common/auth/auth.service.ts
- packages/backend/src/app/common/workspaces/workspaces.controller.ts
> feat(auth): Include project to user during registration

- packages/frontend/src/components/project-management/cards/BaseCard.vue
- packages/frontend/src/composables/useCommands.ts
> feat: toggle info drawer command shortcut

- packages/frontend/src/components/common/inputs/BaseUserSelector.vue
- packages/frontend/src/components/project-management/views/ListView/ListViewGroup.vue
- packages/frontend/src/components/project-management/views/TableView/TableViewGroup.vue
> fix: previously selected users are not set as selected in v-autocomplete

- packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilterItem.vue
> fix(filter): Handle reset filter

- packages/frontend/src/components/common/auth/LoginPage.vue
- packages/frontend/src/pages/index.vue
> Feature: Post-login Navigation

- package-lock.json
- packages/frontend/package.json
- packages/frontend/src/components/common/base/BaseEditor/BaseEditorInput.vue
- packages/frontend/src/components/common/base/BaseEditor/extensions/CustomKeymap.ts
- packages/frontend/src/components/common/dialogs/CreateCardDialog.vue
- packages/frontend/src/components/common/inputs/BaseDatePicker.vue
- packages/frontend/src/components/project-management/cards/BaseCardCommentBox.vue
> feat: chores

- packages/frontend/src/composables/useHideNavigationDrawer.ts
- packages/frontend/src/layouts/CrmLayout.vue
- packages/frontend/src/layouts/ProjectLayout.vue
> Fix: Always Hide Navigation Drawer when Necessary

- packages/backend/src/app/common/auth/auth.controller.ts
- packages/backend/src/app/common/auth/auth.service.ts
- packages/frontend/src/components/common/auth/RegisterForm.vue
- packages/frontend/src/composables/services/useAuthService.ts
- packages/frontend/src/pages/invite/[inviteCode].vue
- packages/frontend/src/stores/auth.ts
> Fix: Handle join project for registered users

- packages/backend/src/app/common/helpers/query.builder.helper.ts
- packages/backend/src/app/common/lists/list-groups/dto/create.list.group.dto.ts
- packages/backend/src/app/common/lists/list-groups/list.group.entity.ts
- packages/backend/src/app/common/lists/list-groups/list.groups.service.ts
- packages/frontend/src/components/common/fields/BaseField.vue
- packages/frontend/src/components/common/inputs/BaseDatePicker.vue
- packages/frontend/src/components/common/inputs/BaseDropdownInput.vue
- packages/frontend/src/components/common/inputs/BaseLabelSelector.vue
- packages/frontend/src/components/common/inputs/BaseNumberInput.vue
- packages/frontend/src/components/common/settings/CustomFieldsSettings.vue
- packages/frontend/src/components/project-management/views/BaseViewChipFilter/AdvancedFiltersItem.vue
- packages/frontend/src/components/project-management/views/BoardView/BoardViewGroup.vue
- packages/frontend/src/components/project-management/views/ListView/ListViewGroup.vue
- packages/frontend/src/components/project-management/views/TableView/TableViewGroup.vue
- packages/frontend/src/composables/useCard.ts
- packages/frontend/src/composables/useFields.ts
- packages/frontend/src/composables/useInputs.ts
- packages/frontend/src/plugins/vuetify.ts
- packages/frontend/src/utils/validation.ts
- packages/shared/src/lib/fields/index.ts
- packages/shared/src/lib/filters/index.ts
> feat: new custom field types

- packages/frontend/src/components/project-management/views/ListView/ListView.vue
- packages/frontend/src/components/project-management/views/ListView/ListViewGroup.vue
- packages/frontend/src/components/project-management/views/TableView/TableView.vue
- packages/frontend/src/components/project-management/views/TableView/TableViewGroup.vue
- packages/frontend/src/composables/useListGroup.ts
- packages/frontend/src/services/useListGroupsService.ts
> fix: toggling group expansion does not reflect instantly

- packages/backend/src/app/common/lists/list-stages/list.stages.subscriber.ts
- packages/frontend/src/components/common/dialogs/EditListStagesDialog.vue
- packages/frontend/src/services/useListStagesService.ts
> fix: correct behavior when updating list stages
